version: "3.3"

services:
  database:
    image: postgres
    container_name: postgres-task
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

  backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: tasks-api
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"